# Generated by Django 2.2.5 on 2019-09-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ('-id',), 'permissions': (('can_own_stock', 'Can own stock'), ('can_manage_stock', 'Can manage stock')), 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
    ]
