# Generated by Django 2.2.5 on 2019-09-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbalance',
            name='sold',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=20),
        ),
    ]
