# Generated by Django 2.2.5 on 2019-09-22 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190922_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ('-id',), 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
    ]
