# Generated by Django 2.2.5 on 2019-09-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190922_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='active',
        ),
    ]
