# Generated by Django 2.2.5 on 2019-09-22 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_membership_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=9, max_digits=20)),
                ('defect', models.DecimalField(decimal_places=9, max_digits=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_balances', to='main.Product')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_balances', to='main.Stock')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
