# Generated by Django 2.2.5 on 2019-09-22 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_productbalance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbalance',
            options={'ordering': ('-id',), 'verbose_name': 'Product Balance', 'verbose_name_plural': 'Product Balances'},
        ),
    ]
