# Generated by Django 2.2.5 on 2019-09-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190922_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbalance',
            name='balance',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='productbalance',
            name='defect',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=20),
        ),
    ]
