# Generated by Django 2.2.5 on 2019-09-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190923_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbalance',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
